version: '3.8'
services:
    skunexus_nginx:
        image: nginx:alpine
        container_name: skunexus_nginx
        # Choose your ports in docker-compose.override.yml
#        ports:
#            - 80:80
#            - 443:443
        volumes:
        # map path where the project exists on your system in docker-compose.override.yml
        #   - /home/user/code/project:/application
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - skunexus_php
        working_dir: /application
#        networks:
#            - skunexus_lan

    skunexus_php:
        build:
            context: .docker/php-fpm
            args:
                - WITH_XDEBUG=true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: skunexus_php
        volumes:
        # map path where the project exists on your system in docker-compose.override.yml
        #   - /home/user/code/project:/application
            - .docker/data/home/developer:/home/developer
            - .docker/php-fpm/common.ini:/usr/local/etc/php/conf.d/custom-common.ini
            - .docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/custom-xdebug.ini
        working_dir: /application
        environment:
            - PHP_IDE_CONFIG=serverName=localhost
            - XDEBUG_DEFAULT_KEY=PHPSTORM
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
            - XDEBUG_MODE=${XDEBUG_MODE:-off}
            - XDEBUG_START_WITH_REQUEST=${XDEBUG_START_WITH_REQUEST:-trigger}
            - XDEBUG_TRIGGER_VALUE=${XDEBUG_TRIGGER_VALUE:-}
            - XDEBUG_LOG=${XDEBUG_LOG:-}
#        networks:
#            - skunexus_lan

    skunexus_db_sql:
        image: mysql:8
        restart: always
        container_name: skunexus_db_sql
        volumes:
            - .docker/data/db/mysql:/var/lib/mysql
        # Choose your ports in docker-compose.override.yml
        #        ports:
        #            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_HOST: "%"
        command: mysqld --innodb-flush-method=O_DSYNC
#        networks:
#            - skunexus_lan

#networks:
#    skunexus_lan:
